name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers pipeline when pushing to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/nodejs-demo-app .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image to DockerHub
        run: docker push your-dockerhub-username/nodejs-demo-app

