name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Convert DOCKER_USERNAME to lowercase
        run: echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]' > DOCKER_USERNAME_LOWER

      - name: Mask Secrets for Security
        run: echo "::add-mask::${{ secrets.DOCKER_PASSWORD }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$(cat DOCKER_USERNAME_LOWER)" --password-stdin

      - name: Build Docker Image
        run: docker build -t my-web-app .

      - name: Tag Docker Image
        run: docker tag my-web-app "$(cat DOCKER_USERNAME_LOWER)"/my-web-app:latest

      - name: Push Docker Image to Docker Hub
        run: docker push "$(cat DOCKER_USERNAME_LOWER)"/my-web-app:latest

